### ISSUE TITLE
plist formatting issue

### ISSUE THREAD

**Issue by catmclough** [rtoohil/Reading-List-to-Instapaper#6]
plist must have opening tag
`<plist version="1.0">`
(See: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/PropertyLists/UnderstandXMLPlist/UnderstandXMLPlist.html)

Otherwise we get
`com.ryantoohil.readinglisttoinstapaper.plist: Invalid property list`

I tried to open a pull request but got a 403.

**Comment by rtoohil** [comment]
Thanks!

Clearly, I haven't done too much with this (share sheets in iOS obviated my need for this), but I'll see if I can't get a commit with that in the next day or so.

I'm not sure why it threw a 403 on a pull request -- must be some sort of GitHub issue.

**Comment by rtoohil** [comment]
I haven't tested this, but this should be pretty innocuous.

**Comment by catmclough** [comment]
Thanks! 😁
